#+TITLE: Wire Cell Toolkit Configuration

* What is here

This repository holds Wire Cell Toolkit configuration support files
and some configuration sets.

For more information see the [[https://github.com/WireCell/wire-cell-docs/tree/master/manuals/configuration.org][WCT configuration manual]].

* Contents overview

** General support files

Files at top level provide general support and utilities.  Primarily
there is the file:

- [[./wirecell.jsonnet]] 

This holds a Jsonnet version of the WCT /system of units/ (which is
essentially identical to CLHEP's).  It also includes a number of
Jsonnet functions to form some common configuration data structures.

** Configuration file sets

A number of configuration file sets are provided in subdirectories.
Each targets some particular job, may be used as examples or copied
and adapted.  Configuration file sets may employ various
organizational structure but in general there is a top level file that
provides the final WCT configuration sequence which references data
structures defined in lower level files.  Examples include:

- [[./uboone/nfsp/]] configures a noise filtering and signal processing.
  The [[./uboone/nfsp/magnfsp.jsonnet][magnfsp.jsonnet]] is the main file to give to =wire-cell=.  This
  will use Magnify files as input and output.  The other low-level
  files can be used as-is to run an almost identical job in LArSoft
  which will use the =art::Event= data structure as input and output.
  The equivalent to =magnfsp.jsonnet= can be found in the
  =larwirecell= package.

- [[./uboone/fourdee.jsonnet]] is a main file for setting up a simple
  "four D" simulation with MicroBooNE wire geometry.  

- [[./multi/main.jsonnet]] is the main file for setting up "multiductor"
  simulation.  It uses files under [[./uboone/]].


* Tests

Running the configuration tests is done through the files under =test/=.  They rely on a simple ad-hoc test harness. All tests can be run from the top-level =wire-cell= source directory after a build like:

#+BEGIN_EXAMPLE
  ./cfg/test/test_all.sh
#+END_EXAMPLE

A single test can be run like:

#+BEGIN_EXAMPLE
  ./cfg/test/test_one.sh <testname>
#+END_EXAMPLE

Each test has a =test_<testname>.jsonnet= file.

#+BEGIN_EXAMPLE
  ls cfg/test/test_*.jsonnet
#+END_EXAMPLE

These main JSonnet files are typically composed of some chunks reused by the various different tests. The chunks are named like =cfg_*.jsonnet=.  The body of each main =test_<testname>.jsonnet= largely consists of the data flow graph definition for the =TbbFlow= Wire Cell application object.
