#+TITLE: Wire Cell Toolkit Configuration

* What is here

This repository holds Wire Cell Toolkit configuration support files
and some configuration sets.

For more information see the [[https://github.com/WireCell/wire-cell-docs/tree/master/manuals/configuration.org][WCT configuration manual]].

* Contents overview

** General support files

Files at top level provide general support and utilities.  Primarily
there is the file:

- [[./wirecell.jsonnet]] 

This holds a Jsonnet version of the WCT /system of units/ (which is
essentially identical to CLHEP's).  It also includes a number of
Jsonnet functions to form some common configuration data structures.

- [[./vector.jsonnet]] 

This holds some functions to assist in doing vector arithmetic in Jsonnet.

** Configuration file sets

A number of configuration file sets are provided in subdirectories.
Some organizational guidelines:

- Do keep file sets self contained to a sub-directory.

- Do not cross-reference files in other sub-directories.

- Do reference (~import~) general support files from the top level
  directory.

- Feel free to organize into sub-sub-directories.

Some examples include:

- [[./uboone/nfspl1/]] config for MicroBooNE noise filter and signal
  process with support for grounded wires ("L1").  See also testing
  config under [[./l1sp]].

As jobs or configuration organization styles become outdated their
sub-directories are moved under [[./obsolete/]].  Avoid using these but
they may hold historical significance for past processing.

There may be other Jsonnet files found in the ~/test/~ sub-directories
of the various WCT packages.

* Tests

Running the configuration tests is done through the files under =test/=.  They rely on a simple ad-hoc test harness. All tests can be run from the top-level =wire-cell= source directory after a build like:

#+BEGIN_EXAMPLE
  ./cfg/test/test_all.sh
#+END_EXAMPLE

A single test can be run like:

#+BEGIN_EXAMPLE
  ./cfg/test/test_one.sh <testname>
#+END_EXAMPLE

Each test has a =test_<testname>.jsonnet= file.

#+BEGIN_EXAMPLE
  ls cfg/test/test_*.jsonnet
#+END_EXAMPLE

These main JSonnet files are typically composed of some chunks reused by the various different tests. The chunks are named like =cfg_*.jsonnet=.  The body of each main =test_<testname>.jsonnet= largely consists of the data flow graph definition for the =TbbFlow= Wire Cell application object.
